version: 2
jobs:
  fedora40:
    working_directory: ~/libreadtags
    docker:
      - image: docker.io/fedora:40
    steps:
      - run:
          name: Install Git
          command: |
            yum -y install git
      - checkout
      - run:
          name: Install build tools
          command: |
            yum -y install gcc automake autoconf libtool make
      - run:
          name: Build
          command: |
            bash ./autogen.sh
            ./configure
            make
      - run:
          name: Test
          command: |
            make check VERBOSE=1
  fedora40_distcheck:
    working_directory: ~/libreadtags
    docker:
      - image: docker.io/fedora:40
    steps:
      - run:
          name: Install Git
          command: |
            yum -y install git
      - checkout
      - run:
          name: Install build tools
          command: |
            yum -y install gcc automake autoconf libtool make
      - run:
          name: Build
          command: |
            bash ./autogen.sh
            ./configure
      - run:
          name: Test
          command: |
            make distcheck
workflows:
  version: 2
  build_and_test:
    jobs:
      - fedora40
      - fedora40_distcheck
